apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogeyJhdXRoIjogIlpISjFibXRsYm1SdmJIQm9hVzR5TFdGcE9tZG9jRjlaZDAxT1lVcEVPWEZ5Y1VodU4zSnZla1JpYzNoSGRHOHpjbkE0U0hBemF6ZGhSRFk9In0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0sCgkJImFpIjogewoJCQkiaG9va3MiOiAiYnVpbGQsYnVpbGR4IGJ1aWxkLHJ1bixjb21wb3NlIgoJCX0sCgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9LAoJCSJzY291dCI6IHsKCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
